let
    TenantId = "PASTE_YOUR_TENANT_ID_HERE",
    ClientId = "PASTE_YOUR_CLIENT_ID_HERE",
    ClientSecret = "PASTE_YOUR_CLIENT_SECRET_HERE",
    A3FacultySkuId = "PASTE_YOUR_SKU_ID_HERE",

    // Get an access token
    TokenUrl = "https://login.microsoftonline.com/" & TenantId & "/oauth2/v2.0/token",
    TokenBody = "client_id=" & ClientId 
              & "&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default"
              & "&client_secret=" & ClientSecret
              & "&grant_type=client_credentials",
    TokenResponse = Json.Document(Web.Contents(TokenUrl, [
        Content = Text.ToBinary(TokenBody),
        Headers = [#"Content-Type" = "application/x-www-form-urlencoded"]
    ])),
    AccessToken = TokenResponse[access_token],

    // Recursive function to handle paging through all users
    GetAllUsers = (url as text) as list =>
        let
            Response = Json.Document(Web.Contents(url, [
                Headers = [#"Authorization" = "Bearer " & AccessToken]
            ])),
            CurrentPage = Response[value],
            NextLink = Record.FieldOrDefault(Response, "@odata.nextLink", null),
            AllUsers = if NextLink <> null 
                       then CurrentPage & @GetAllUsers(NextLink) 
                       else CurrentPage
        in
            AllUsers,

    // Fetch all users with the fields we need
    StartUrl = "https://graph.microsoft.com/v1.0/users?$select=userPrincipalName,assignedLicenses,accountEnabled&$top=999",
    AllUsers = GetAllUsers(StartUrl),

    // Convert to table
    UsersTable = Table.FromList(AllUsers, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    ExpandedUsers = Table.ExpandRecordColumn(UsersTable, "Column1",
        {"userPrincipalName", "assignedLicenses", "accountEnabled"},
        {"UPN", "AssignedLicenses", "AccountEnabled"}),

    // Extract domain from UPN (everything after the @)
    WithDomain = Table.AddColumn(ExpandedUsers, "Domain", each 
        let upn = [UPN] in
        if upn <> null and Text.Contains(upn, "@") 
        then Text.AfterDelimiter(upn, "@") 
        else "unknown"),

    // Check if user has A3 Faculty licence
    WithA3Flag = Table.AddColumn(WithDomain, "HasA3Faculty", each
        let licences = [AssignedLicenses] in
        if licences = null then false
        else List.Contains(List.Transform(licences, each _[skuId]), A3FacultySkuId)),

    // Filter to only A3 Faculty holders
    OnlyA3Users = Table.SelectRows(WithA3Flag, each [HasA3Faculty] = true),

    // Group by domain and count
    GroupedByDomain = Table.Group(OnlyA3Users, {"Domain"}, {
        {"A3FacultyCount", each Table.RowCount(_), Int64.Type}
    }),

    SortedResult = Table.Sort(GroupedByDomain, {{"A3FacultyCount", Order.Descending}})
in
    SortedResult


Quick test  